[profile.default]
src = "src"
out = "out"
libs = ["lib"]
via_ir = true
optimizer = true
optimizer_runs = 200
evm_version = "cancun"
timeout = 120000
block_timeout = 15
gas_limit = 30000000
gas_price = 500000000000
remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "forge-std/=lib/forge-std/src/"
]
